# Generated by Django 4.1.5 on 2023-02-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='username',
            field=models.CharField(default='username', max_length=200),
        ),
    ]
